[package]
name = "pandorast"
version = "0.1.0"
authors = ["M Esteban Fernández"]
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
toml = "0.5.8"
serde = {version = "1.0.133", features = ["derive"]}