FROM rust:latest AS builder

RUN rustup target add x86_64-unknown-linux-musl
RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates

WORKDIR /pandorast
COPY ../. .
RUN cargo build --target x86_64-unknown-linux-musl --release



FROM alpine

WORKDIR /pandorast
COPY --from=builder /pandorast/target/x86_64-unknown-linux-musl/release/pandorast ./

CMD ["./pandorast"]